name: 'Terraform Plan'

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "destroy*"
  pull_request:

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [test, prod]
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_CLIENT_TENANTID }}
      TEST_ARM_SUBSCRIPTION_ID: ${{ secrets.TEST_AZURE_AD_CLIENT_SUBSCRIPTIONID }}
      PROD_ARM_SUBSCRIPTION_ID: ${{ secrets.PROD_AZURE_AD_CLIENT_SUBSCRIPTIONID }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Terraform environment variables
        run: |
          if [ "${{ matrix.environment }}" == "test" ]; then
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.TEST_AZURE_AD_CLIENT_SUBSCRIPTIONID }}" >> $GITHUB_ENV
          elif [ "${{ matrix.environment }}" == "prod" ]; then
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.PROD_AZURE_AD_CLIENT_SUBSCRIPTIONID }}" >> $GITHUB_ENV
          fi

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "."

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "."
          
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "."
